apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pulumi-pg-patroni
  namespace: pulumi-kubernetes-operator
spec:
  interval: 5m
  url: https://github.com/rassulamangeldi/one-click-openstack-infrastructure.git
  ref:
    branch: master
  ignore: |
    # Exclude everything except pg-patroni directory
    /*
    !/pg-patroni
