apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pulumi-kubernetes-operator
  namespace: pulumi-kubernetes-operator
spec:
  releaseName: pulumi-kubernetes-operator
  chartRef:
    kind: OCIRepository
    name: pulumi-kubernetes-operator
    namespace: pulumi-kubernetes-operator
  interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    podSecurityContext:
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 0
    rbac:
      create: true
      createClusterRole: true
      createRole: false
      createClusterAggregationRoles: true
      extraRules:
        - apiGroups: [""]
          resources: ["pods/exec", "pods/log"]
          verbs: ["get", "list"]
        - apiGroups: ["authentication.k8s.io"]
          resources: ["tokenreviews"]
          verbs: ["create"]
        - apiGroups: ["authorization.k8s.io"]
          resources: ["subjectaccessreviews"]
          verbs: ["create"]
