apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pulumi-kubernetes-operator
  namespace: pulumi-kubernetes-operator
spec:
  interval: 120m
  url: oci://ghcr.io/pulumi/helm-charts/pulumi-kubernetes-operator
