apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pulumi-kubernetes-operator
  namespace: pulumi-kubernetes-operator
spec:
  releaseName: pulumi-kubernetes-operator
  chartRef:
    kind: OCIRepository
    name: pulumi-kubernetes-operator
    namespace: pulumi-kubernetes-operator
  interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # values:
