apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: pulumi-kubernetes-operator
  namespace: pulumi-kubernetes-operator
spec:
  interval: 120m
  url: oci://ghcr.io/pulumi/helm-charts/pulumi-kubernetes-operator
  ref:
    tag: 2.0.0
  
