apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: pg-patroni-stack
  namespace: pulumi-kubernetes-operator
spec:
  stack: test-devopsdays/pg-patroni
  projectRepo: https://github.com/rassulamangeldi/one-click-openstack-infrastructure.git
  branch: master
  repoDir: pg-patroni/
  destroyOnFinalize: false
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: accessToken
  retryOnUpdateConflict: true
