node: 10.129.1.221
metadata:
    namespace: config
    type: MachineConfigs.config.talos.dev
    id: v1alpha1
    version: 1
    owner:
    phase: running
    created: 2025-03-20T07:17:50Z
    updated: 2025-03-20T07:17:50Z
spec: |
    version: v1alpha1
    debug: false
    persist: true
    machine:
        type: controlplane
        token: pucfxb.9wqqobm4axzssgwo
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEF1aktQT1JVWDRaUEtldkN5NlFSWEZNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5UQXpNakF3TnpFM01qRmFGdzB6TlRBek1UZ3dOekUzTWpGYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBbDhzZ1c2Mm9OdUxSaFJGNW8vaG5MS0xTUWYyTDE1bCtJbCtQCnl2bWNsLzJqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVWGIrcWFYL01KNnF2Ny9DWApiYVZWL05wN2pQVXdCUVlESzJWd0EwRUFMQ0trR1FZUTBiMnpYdXoybnQ4eTk5bWlySHFETGg2SFZVSTF6RmxHCnJHTzBHU0tocUpHY1hwOXNWUmZKMSt1ZCtDSXdhcVhKUlllY3RVNW5rc3dWRGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
            key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJQzhzWFB6bUxrQVA0MDlIVnpvenFBQjNUMm5pVC9ydjdzcGsrbnZCY3pXdAotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
        certSANs: []
        kubelet:
            image: ghcr.io/siderolabs/kubelet:v1.30.1
            defaultRuntimeSeccompProfileEnabled: true
            disableManifestsDirectory: true
        network:
            interfaces:
                - deviceSelector:
                    physical: true
                  dhcp: true
            nameservers:
                - 1.1.1.1
                - 8.8.8.8
            disableSearchDomain: true
        install:
            disk: /dev/vda
            image: ghcr.io/siderolabs/installer:v1.7.4
            wipe: false
        files:
            - content: |-
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
                [plugins."io.containerd.grpc.v1.cri".containerd]
                  discard_unpacked_layers = false
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                  discard_unpacked_layers = false
              permissions: 0o0
              path: /etc/cri/conf.d/20-customization.part
              op: create
        time:
            disabled: false
        sysctls:
            fs.inotify.max_queued_events: "65536"
            fs.inotify.max_user_watches: "524288"
            net.core.rmem_max: "2500000"
            net.core.wmem_max: "2500000"
        features:
            rbac: true
            stableHostname: true
            kubernetesTalosAPIAccess:
                enabled: true
                allowedRoles:
                    - os:admin
                allowedKubernetesNamespaces:
                    - system-upgrade
            apidCheckExtKeyUsage: true
            diskQuotaSupport: true
            kubePrism:
                enabled: true
                port: 7445
            hostDNS:
                enabled: true
    cluster:
        id: gJ4IA7HRtkxVmJplIFCgAibO-b9l7-MK5qWgkfsxtYA=
        secret: WUIRE9OoZeYoz/3YEQzIOhhgK2PpXaLygD2/MVe/wkY=
        controlPlane:
            endpoint: https://10.129.1.221:6443
        clusterName: test-devopsdays-talos
        network:
            cni:
                name: none
            dnsDomain: cluster.local
            podSubnets:
                - 10.244.0.0/16
            serviceSubnets:
                - 10.96.0.0/12
        token: qele20.gxm518y6hrpkpmxj
        secretboxEncryptionSecret: gMAZpux1aMvn3+leHGgyFJNWuUz8NmJlzzUX+tBC4JA=
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRDZ0F3SUJBZ0lSQU5hUWMySlNDSjJLWVdUd3d5bTdjNll3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEF6TWpBd056RTNNakZhRncwek5UQXpNVGd3TnpFMwpNakZhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRhRlJiaCtyUWYrMjNGMFVrWUx5MGVkVHNORmRaQVVxcStpSStIUmlYNDBkMndFbW1oOUpKMVdrVm0KbFZhOHkydzlrTHVLYnVNVUdqWFRCRFRPZGtkZG8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGT2lmQkMzblNVdkJhZFB2dnRVaGhnZXR5N1BlTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDVEhrMk8KTU9KU2ZEUXhPQWhnTVdOc1pnamJqN1dUcFNhYUd5eE0zWDR1K1FJaEFLRUZNU0gxVzRMQy9WS1Q5U1BXeGZBTApDZm1jbTdYV3pnNmV1MTRDTVBOYwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUJublExUFVmaG15OGZqWkhQaFRlK0pYQzBmYVA2TjVJeWhtdzdzRmJUaURvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMmhVVzRmcTBIL3R0eGRGSkdDOHRIblU3RFJYV1FGS3F2b2lQaDBZbCtOSGRzQkpwb2ZTUwpkVnBGWnBWV3ZNdHNQWkM3aW03akZCbzEwd1Ewem5aSFhRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
        aggregatorCA:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYakNDQVFXZ0F3SUJBZ0lRWjRXKzhSc1BKdEs5V2wyaXdCWExOREFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMU1ETXlNREEzTVRjeU1Wb1hEVE0xTURNeE9EQTNNVGN5TVZvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCRmhtOU1zWXdiUDl5Tlh0cVBKNXVPRENLQU9vSXJ2djcyR2c0WENldldMWkRVUzFBZmNiCng4WllzL2t2UFhTRXJjL2tmNlpYUjMyM1ZuZ0dWMXdJOFVLallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVqTnQybXVDZXQvOGpqK2ExZFc4MmovbW8xaDh3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnClNQQU0vWGlnOEl1dHk5V294NldhdytoMjdWZTNnRTVJcnE1UXZ0dmkzNXNDSUc3OTAxSVM1WFZXeVEvb0p5YlQKVjBNSnhGQXJ0eDl3VUl6WU91dVp3dVFrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdyakdQZjk4R1lCQU1mNGpJWXhOdS9aWWI3VkYwWTdjMlczVXJsUzlFdytvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFV0diMHl4akJzLzNJMWUybzhubTQ0TUlvQTZnaXUrL3ZZYURoY0o2OVl0a05STFVCOXh2SAp4bGl6K1M4OWRJU3R6K1IvcGxkSGZiZFdlQVpYWEFqeFFnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
        serviceAccount:
            key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS3dJQkFBS0NBZ0VBM3dKNXREMlFjMTJpdkdvNjBObFZNV29hRVBoRktiZUpiRWIzVG1tTXFMQ0ZzSE5kCmxJdC9TNFJSM0F4dWY2cHFvUXNyQVpIMytCYVFoYlRoTW5JYzZoQjlEaS9aTXBHcEVic3VjL1pDcjFaeUJRK1EKdmYxZTFYeWgrN09ZbjNEdjJNS1dSUWdtV3BaYTgrTHJGZHBuY3hDVnRWdVRrNFNDR3VTNTlGUXo4b2U2a0drZApLcm1rVWs2ZWNaaUY5YjVRK0NsdWdiWk1ndlFmMHN1ck9qdDZpNS95enpiSVEzdzdnU0xxQkQ3M3dQWnVvdXZHCmNUTXg3dWJSbVpFcDBVUEk0Ry9pME8yK2l3UkZTVmxNQXdkcXl4ZGlGL1Zrb2N5eVZ2KzNhR2tmcjhkRXJnbUMKeEhiTi9HeWsyaG1rMW9YTy85clBiKzN2MVlkdUVQZThJUlAvQk5oOEwwTWxJb0Y5bWgyeThzOHBSaWhqdm1rSwo0Y2MyOGI4WmxjZ2tOSThXRGZ1d3V1ZnlHeWV0NGY2dlNxQ2NuMnFwdGZzVXc5U1pSc2o5TWxtcWEzWkYwbVVPCjBTUlFGSW1adEZxNCt1anl3S2h1TFhTWGlvZ1FaaDg0UmRLa0x6anhpSURxa24vMVZGWVJCOUE4YUpkTWxJY2kKRHN0T1dZcWluS3lqUXQxV21Mekxia3RVMGNBNjhoOFBCb0NwVHVHRzFHSXRZVUFMZHplVkFzbjR0OWV4OEprTApobXg4ejZXbFljUnBLWEpxVktDNjdrdk51eEtQN1BKZml6VHRjaDRJcDJzc1RGeDNGejlQVjhrWEdCNUovVXZyCklXZmdvSHJTNFREVkpiTllNelVLZHhja1Q4OTZ0cllEQ3VjVTBEMllVaDdzek1iYUNFaTNVRlpSa1cwQ0F3RUEKQVFLQ0FnRUEzbFgrZHBkbWU4NWYzODlkUWpsYnVYOVo2NDlLalRQaCs2U3BEWEVuL2txM2p0c0Y4b0k5Y0ZIRQp0MGxocFVDSFBIWUE4M2pQSzNWN3N3SkovdHhNUFlRZzJkTVVqVmt4b1c3bitrOEwzdm1saGF3bUYzVVRabTd5CnBCcERVTHJ0TlVPVFE5SERRMDloOElOTTg2V2l1OUpPSDlqa1FnKzdFd3IwNWtaSTRFVTMyS0FqcHlRY1VyNzEKTXJYbzRMOVV4SVd5R2ZwaFA3SWFSRFF3UzBkZmZ2TUJ4bHVNdjlPTkU4dDJXck5ZbVBaWUNYQmRrU0NFYVBXUgpCTFQ0WngxWW1ZS1ROTS9DeDZDRFg0UjZ4dzVQQjVvUmYyZDFZK2JMNnZiWnFXd2RYa2VpRG8yRzVVNjVRVEFrCkR4bkFBT3k1R3RiUk4zdVdRR0hjZDJnMkZSaDFoMGQyeWdzYVRjQzFaaWJ2YkUrM28yalA0b3pTT3FOeVduYzEKcTBMZmQvTkhzV2hCM1I4blF4VnhTVU5CMWN0Nkg3R1p5bWNkdmkzOTd6WE9SWVk1RVMwaVJEVWZqcXRieURrYQpIMDlMeEdzYWRUKy8wbFppLzcxUlFPMWt3aU5NTzlwLzZRQVhSNVpKeU1pS0dKMjlLNDB1MDJBRHFpaEl3YkhaCmJncFhRRE1OMU56QjNqYnhyODREaUp3S0Z2Yi9IMWVjcStybzk0dDZrQTNMU3hHL2x5M0dzbzEzRDNlSmgxTmgKbTlnNEs0TVpCdm9iUVV2eTFBK29SMDRraTIxSHkvR0h4NUMwMGdaMjZQVUZJWCs0bWM2RVFKTUExejFiWUZSNgpTd1dpVWNsNnI2RURNV3UycHNhbmR2OWp5SDhDN3IySW1FWEhmM2RmNTAyMkNKd2VWcUVDZ2dFQkFPWTd1Mms0CjV2eEpEbHFTVERhL0wwU2xFd3A2SGNSY1l4eEd0eEVaRFA5OHpTTzdldWF2MHB1OXBvUkxNc2ZUc3F2RzhGQUIKemdHbjE0Rkg0a3RIMjJYRjBwMCtqdXlKeWdKbWJHcnNJUGJ6WTR1dDVUUzFnN3JJbisvdGtMOUp2RFBhcmtESQpSL1VGS1dRRlpnTXZCbU1sNVhxY3JYWldtVVQ5Tzl5RTFqbjNCbEZmeElLVnNYcHBaMGtCT0VOYmZhTVJmTG9ECkt5ZXphbDdqdjF6WjJWcXdvM3RzQnBwNjZCc09RdUt5bi80R2MyYlpvc0wwTFNCbXliVTVFd01iV1RTRmphaDMKbGdPbjhkN04xRW5QZzZxQngrem1FSitsYkF1dlQ0RUdMR1p3V2liRDFrZE56L0dEZnFHY1hDZWNpREc0cTUzLwpXNEtHelZCSFBCWG1DRmtDZ2dFQkFQZjN5R3djWWJlV0tnV1VOa2JYWGRybmtudTFhY0M0cktaYmRGbW1qbEx0CjdFLzFVcTZkVFZudVlWajlTcStZVHlubG90NWpUVnFRcjZCOEpieFMwbzEydUV4cWlTVnd1eHJ5b2NhRUFTeFEKWFJlSE1UcjE1dmg0QkJCREpMazJ0bDR1cGcvNDh3MEs2blVZbVovczN1VEFOS0Y1OTJCN3N0U3lWZVR5S1FrTAp5QVlVOHhWWEtvWUJtVEdIZitIcmFDemV5MGFPTnBoSVpVUmd5S0dWbE9vRlVPQmF2UGw0UnNUMkdyKzBXZ3FpCjliRi9ISk9Db2d3a3l1N0dUcUFCcWtzUGNhbmROY2VXZFZVYXB0S2NtMXI2RDZTN1M4VnRibVhqMUNNRVNlZ2kKMUZYeDlUampSRE8rL1NnMEkvZmhReFNXQlFsTW5VSk9Ub0RhdC81RnJ6VUNnZ0VCQU9WcUw5MHhyamxHTXQ5ZApXRVJWVGF5Qk1QQUhyeEd6WGE4WForUEpxb0lLd2Y4UkdlNDAxUkFMY3Bud3RMRVo2YmZ4akJTdE43RytwYWRWCkVkRWgwU1VnY2pYdDJFMHJIL2cwUjJSajFwVTlBYngxa3lkcWw5RFBpVTl5MGdGS1lCYnJtU2RFYXk5ajdWS1YKYm9sTm1uZkJrMkVTTG1iMDg5VWk0VHRqd25RUUNtT2JvaHpkUFBSVmcyM2pvVVM5TGZ3SHVObEJ2d2JZYU80VQowdUthMFZMbElJSWpxcERVVitSZDJaZzdsZUZ5WEJ2b1VaOGg0TFdndHUyMTZaUDI5SFM1ZithWEF3eXhsUG9HCjc3cDg1UjVLSkFXVFdvMDZNT2VUMFEwb01hWUIzbE15WVpxN2xyRjU3ZnpyNllndkdpY3hkUkVER3hSOWJxakgKMHIrZmNFRUNnZ0VCQUtZRXFaVm9jeXdkUjhrd2NCNkI5djZtNkhZWEFkVGNVQXVaVTQ3cWFvT3ZjL1ljdzl6UQp5SWNiaU9XeHdCMU1sa1B3MFZpZmw1eTVIajBPb1oweXZuR2tPTVJBMTgzUGFoWWl1SmxXckFwbFM4NkMzejBnCmdpRjlDUXR5U05ZUWdZMFJJbkd6TmRkWHBaMzhlRzZRZ3JNWTFLUUFLdFhZTytVWCtWWXRvN2ZBd1kwQTNiYysKQXVSeGtZV051TnNqWno0VGRIbXFvWGJYa2FWMFB4K2dMSEY2V2FtOFZxV1lGNW1yUkVGeG1JOWloNmpzOTg3egpPVmQwRXNKRzEwRmRuQXhoTExLVHZud0FpbElPWS83Q2gya2ozdkZsek5kRDZ4UWdzMWsyZDkwSjVLd2VNUmFECllwaGFtTmdnQUt6bmpxZnJ3VGQycWh0SW5scTdGVkVTaXJrQ2dnRUJBTHBleXFoanhDMFZWWVM2QWlQTFRSd08KbGdwUndob2JGKzQ0eEtEWGFvT1M3OUw3TUhOKzBtcDVkRDhCVzl4QU9iZXB3NVkvUHZoVDZIOWRCcU42TjhHMwpjdkdVdU8rMWpYdjFhMm12Rnd3VVFncXIydVlzeTl2eXRIdGVxeXNTeUhUL1BoeG5rNlNHM1pHVTdsSkQrVTBtCmdSNkoveVRFZUw2RXBxTi8yL0NvZ255cExWMFY1T0JBT1NITFM3N2dic1hPb3dBNnJXSTdpQ1hYMFVwQURUMXUKdFg0aVJSNisrSExXT0tpY2NNOGdFaVhZWjc4QzZFVGh6dCt1R0tqSnI1RWxHRDFOY1JTTDREMDhNMVAyTldIUwpOOFY5T0phYk5tY1VIaDQxZGpyakJobXlHYkxNMVBjZEdKVDZIRENBdmdMVlAyaktjWXpDakRBemNOYnkwL289Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
        apiServer:
            image: registry.k8s.io/kube-apiserver:v1.30.1
            certSANs:
                - 10.129.1.221
                - https://10.129.1.221:6443
            disablePodSecurityPolicy: true
            auditPolicy:
                apiVersion: audit.k8s.io/v1
                kind: Policy
                rules:
                    - level: Metadata
        controllerManager:
            image: registry.k8s.io/kube-controller-manager:v1.30.1
            extraArgs:
                bind-address: 0.0.0.0
                terminated-pod-gc-threshold: "1000"
        proxy:
            disabled: true
            image: registry.k8s.io/kube-proxy:v1.30.1
        scheduler:
            image: registry.k8s.io/kube-scheduler:v1.30.1
            extraArgs:
                bind-address: 0.0.0.0
        discovery:
            enabled: true
            registries:
                kubernetes:
                    disabled: false
                service:
                    disabled: true
        etcd:
            ca:
                crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmRENDQVNPZ0F3SUJBZ0lRTGE0ZGVFZnBCa2J4RG4ySnFtSVVuakFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkxTURNeU1EQTNNVGN5TVZvWERUTTFNRE14T0RBM01UY3lNVm93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkthTEJuSC9IdHllCkhINFhBZ0dpMndvK2pkb3VlWWFDdUVRdDRCb1pWZjRBc1kzblFCVVp6c2tBbVk2K1B5enpBR1lVcVlxWHUydUEKeTkwdzhOQmtzTENqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVSXlmMGxMb2VjdGtSCkZqTnFacVQwN3pMS2ZLb3dDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdNeXpnK3NhR3UzTGRhUllBMGFLZDhqWWMKQmlvVHVrZTVpTzhYRzNaalFZc0NJRGNYTmJNaG5qMGFqanFyU29NSlBTTFRFWUNZVkVwTU9SYzJMWmplZEQxaAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
                key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUduZElCdEJETHBnSUZXWVp2Y0I4bmxTNy8xVWE3UDJSbXlJMXdrUFp1dG1vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFcG9zR2NmOGUzSjRjZmhjQ0FhTGJDajZOMmk1NWhvSzRSQzNnR2hsVi9nQ3hqZWRBRlJuTwp5UUNaanI0L0xQTUFaaFNwaXBlN2E0REwzVER3MEdTd3NBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
            extraArgs:
                listen-metrics-urls: http://0.0.0.0:2381
        allowSchedulingOnControlPlanes: true
