apiVersion: v1
kind: Secret
metadata:
    name: test-secret
    namespace: test
type: Opaque
stringData:
    testKey: ENC[AES256_GCM,data:fWzAc68Cej7x,iv:fbd65EaIA8YLE2j/v41//JhluEVlqNK6e8TaXIw9LcI=,tag:OJIlvJfAKo6//Mu9pGJlnw==,type:str]
sops:
    lastmodified: "2025-04-23T11:31:27Z"
    mac: ENC[AES256_GCM,data:DYnrtiKygC6kToa6Eww99rqlDQpcAsh+kK8BYeccDxLUem2JCw72QvZjAxnFVYdcx7GKrr7z/wsA5EDbTkeI1OKqURPRaJ2xufq/d/kgARzo5u1hPlv/2pXNi068UkqwpCuWHq7o8fGDV7qJNssJ9Wr8ZajagLt024cRjkYNkCA=,iv:5Ec6KYJAbqoVPDpBKMqqj/DVyX93IJ1xahfNxWoNiAo=,tag:bYRXFtM99PJP7QisvxzhMw==,type:str]
    pgp:
        - created_at: "2025-04-23T11:31:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5TQL7ymQQEsAQv+Mrk1gl0nEjiL8biDnCTIqlQJd097kW9xpgY9vUje5ykn
            mW41tWqmhtLjMrw40BePYMJYPs6ZSFmRcAgtyyj212Iu/+TTSwpaTy1RPhz3+YJv
            T8zwfjMt3hJrS4KrlYTeSKHuQvpRqbF/YJGzAQN7xgUK4KqX2MBtjQT+jw7tGM57
            ZUL6TWFJ/9t/WU0W8CAtMrOBTqLJvWahwGtlbSque7Zv7GgH+ECOfSsXpU8aFPUF
            QgNsMj4cEdM5cEClU7VTH17EH9ffBnCtPfqOfxtuE6S2RbpFRWx+MT/SL7OGEPXv
            qGWo5iiAIevsqDiaYLy3BLkw4lk38Infn6t3YObuybr44XUJGwbcMpEPyb004AyT
            C8Y00iuCExPA54/VsvsCbr/Prxnh6gyE11cfM9BdVRQBydm69YQIgnO1pDrk6nSw
            DRdmMk/4h+CvLAtB1hxZUnFxYz7r6RbmzvPkEXHkp8d4Z9wsqChOsfUlWgedYPrN
            BZYx8bxtitlfh1qXZbrA1GgBCQIQzOmG4LwN5cnHnxHxDpFlNeiTzl4QqOu/7vrH
            4Rr6eIcxI+r96uAP1sg//Am7WujP54tKRsLZ2NqEmMcGG9bX6+wa8HfC5fqe/07s
            HsQIXy4WdkzG2nSiraAXcK9le6hzyBGLTw==
            =W95a
            -----END PGP MESSAGE-----
          fp: A808795C6D0F0E9F7839800C1567196098551B77
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
