apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap-mongodb
  namespace: flux-system
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ansible-bootstrap
          image: rassulamanngeldi/mongo-ansible-one-click-openstack-infra:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              # SSH keys
              mkdir -p ~/.ssh

              cp /secrets-ansible/test.pem ~/.ssh/test-ssh.pem
              chmod 600 ~/.ssh/test-ssh.pem

              # Install roles and collections
              echo "==== Installing roles adn collections ===="
              ansible-galaxy install -r requirements.yml

              cp -r ~/.ansible/collections /ansible

              ansible-playbook playbook.yaml -i inventory.yaml

              echo "==== Ready to debug in the pod shell ===="
              sleep infinity
          volumeMounts:
            - name: ansible-ssh
              mountPath: /secrets-ansible
              readOnly: false
      volumes:
        - name: ansible-ssh
          secret:
            secretName: ansible-ssh-key
            items:
              - key: privateKey
                path: test.pem

